name: Docker Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: docker.io                                  # Image registry
  IMAGE_NAME: devcontainer                 # Image name comes from repo name

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # This action step reads and updates the version number acc to commit message
      - name: Automated Version Bump                  
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version-bump.outputs.newTag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version-bump.outputs.newTag }}
            type=semver,pattern={{major}},value=${{ steps.version-bump.outputs.newTag }}
          github-token: ${{ secrets.GITHUB_TOKEN }}     

      # Log into the container registry from GitHub runner
      - name: Log into registry ${{ env.REGISTRY }}   
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # GitHub Secret added to the repository
          password: ${{ secrets.DOCKER_TOKEN }}   # GitHub Secret added to the repository

      # Builds and pushes the image to the conatiner registry
      - name: Build and push Docker image            
        uses: docker/build-push-action@v2
        with:
          context: ./                         
          push: ${{ github.event_name != 'pull_request' }}
          # Pushed the image with `latest` tag and the new semantic version obtained from the version-bump step
          tags: ${{ steps.meta.outputs.tags }}
          